"""add_created_by

Revision ID: 0e3d64da1e38
Revises: 26ac0fc764fb
Create Date: 2026-06-02 00:24:44.432324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3d64da1e38'
down_revision: Union[str, Sequence[str], None] = '26ac0fc764fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # CAMBIA esta línea:
    op.add_column('generated_audio', sa.Column('created_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_audio', 'created_by')
    # ### end Alembic commands ###